version: '3'
services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  db-data: {}